### ISSUE TITLE
Wrike integration not working

### ISSUE THREAD

**Issue by nicktoggl** [toggl/track-extension#1922]
#### Relevant integration (if any):
Wrike https://www.wrike.com/

### 🐛 Describe the bug

User reports that the Toggl timer button is not longer appearing in Wrike (since at least March 2nd 2021)

### Expected behaviour

The extension button should appear in Wrike 

[User report ](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481307407648)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481308113583)

**Comment by nicktoggl** [comment]
Any updates on this one?

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481308823443)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309079933)

**Comment by dianetoggl** [comment]
[Case ref](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309728347)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481309749445)

**Comment by dianetoggl** [comment]
[Case ref](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309906308?view=List)

**Comment by edtamayo** [comment]
[Case Reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/3824737/conversation/106481309910025?view=List)

**Comment by edtamayo** [comment]
Per this [Slack conversation](https://toggl.slack.com/archives/C043ZPZQ2JC/p1693258589832269), Wrike has recently revamped their UI to a new UI called Lightspeed, so we'll need to wait for the extension to be enabled on this new UI

Pinging @Alissonsz @nunofmn in case they missed the ping by Apostolos on the thread above. Would you guys be able to implement the extension into the new UI in the near future? I just want to make sure we know if this will be implemented since this issue has gone stale for a while and we have at least 1 team of 10 users requesting the implementation for a while now

**Comment by dianetoggl** [comment]
[Case ref](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309940917?view=List)
